USE zhanLanData;

ALTER TABLE users MODIFY password VARCHAR(255) NOT NULL COMMENT '密码（bcrypt哈希）';

-- 2. 创建评分评论表
CREATE TABLE IF NOT EXISTS ratings (
    user_id INT UNSIGNED NOT NULL COMMENT '用户ID',
    exhibition_id INT UNSIGNED NOT NULL COMMENT '展览ID',
    rating TINYINT UNSIGNED NOT NULL COMMENT '评分 1-5',
    comment TEXT COMMENT '评论内容',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (user_id, exhibition_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (exhibition_id) REFERENCES detailData(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户评分评论表';